<p>Error on Mar 31, 2018 11:36AM - Illegal string offset 'title' in C:\xampp\htdocs\aacet\app\templates\default\header.php on line 24</p><p>Error on Mar 31, 2018 11:37AM - require(C:\xampp\htdocs\aacet\app/views/head.php): failed to open stream: No such file or directory in C:\xampp\htdocs\aacet\app\Core\View.php on line 34</p><p>Error on Mar 31, 2018 12:38PM - ksort() expects parameter 1 to be array, null given in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 126</p><p>Error on Mar 31, 2018 12:39PM - ksort() expects parameter 1 to be array, null given in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 126</p><p>Error on Mar 31, 2018 12:43PM - ksort() expects parameter 1 to be array, string given in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 126</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 08, 2018 16:39PM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '+9196458748' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Helpers\Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Helpers\Database.php(137): PDOStatement->execute()
#1 C:\xampp\htdocs\aacet\app\Models\AuthModel.php(15): Helpers\Database->insert('details', Array)
#2 C:\xampp\htdocs\aacet\app\Controllers\Auth.php(65): Models\AuthModel->register(Array)
#3 [internal function]: Controllers\Auth->register()
#4 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 C:\xampp\htdocs\aacet\app\Core\routes.php(31): Core\Router::dispatch()
#7 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 08, 2018 16:40PM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '+9196458748' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Helpers\Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Helpers\Database.php(137): PDOStatement->execute()
#1 C:\xampp\htdocs\aacet\app\Models\AuthModel.php(15): Helpers\Database->insert('details', Array)
#2 C:\xampp\htdocs\aacet\app\Controllers\Auth.php(65): Models\AuthModel->register(Array)
#3 [internal function]: Controllers\Auth->register()
#4 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 C:\xampp\htdocs\aacet\app\Core\routes.php(31): Core\Router::dispatch()
#7 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 08, 2018 16:41PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fid' in 'where clause'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Helpers\Database.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Helpers\Database.php(109): PDOStatement->execute()
#1 C:\xampp\htdocs\aacet\app\Models\UserModel.php(13): Helpers\Database->select('SELECT * FROM d...', Array)
#2 C:\xampp\htdocs\aacet\app\Controllers\User.php(34): Models\UserModel->getDetails('11')
#3 [internal function]: Controllers\User->home()
#4 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#6 C:\xampp\htdocs\aacet\app\Core\routes.php(31): Core\Router::dispatch()
#7 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#8 {main}</pre>

           <hr />
<p>Error on Apr 08, 2018 17:56PM - require(C:\xampp\htdocs\aacet\app/views/.php): failed to open stream: No such file or directory in C:\xampp\htdocs\aacet\app\Core\View.php on line 34</p><p>Error on Apr 08, 2018 18:12PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 161</p><p>Error on Apr 08, 2018 18:14PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 161</p><p>Error on Apr 08, 2018 18:15PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 161</p><p>Error on Apr 08, 2018 18:18PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 161</p><p>Error on Apr 08, 2018 18:20PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 161</p><p>Error on Apr 08, 2018 18:20PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 161</p><p>Error on Apr 08, 2018 18:21PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 161</p><p>Error on Apr 09, 2018 10:10AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_view.php on line 25</p><p>Error on Apr 09, 2018 10:10AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_view.php on line 25</p><p>Error on Apr 09, 2018 10:10AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_view.php on line 25</p><p>Error on Apr 09, 2018 10:12AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_view.php on line 24</p><p>Error on Apr 09, 2018 10:13AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_view.php on line 40</p><p>Error on Apr 09, 2018 10:14AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_view.php on line 40</p><p>Error on Apr 09, 2018 10:16AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_view.php on line 40</p><p>Error on Apr 09, 2018 16:20PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 161</p><p>Error on Apr 09, 2018 16:21PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_preview.php on line 129</p><p>Error on Apr 09, 2018 16:21PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_preview.php on line 129</p><p>Error on Apr 09, 2018 16:21PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_preview.php on line 129</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 17:26PM</p>

           <p><strong>Message:</strong> Call to undefined method Models\UserModel::deleteChildren()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 55</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->edit()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(32): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<p>Error on Apr 09, 2018 17:26PM - Missing argument 2 for Models\UserModel::deleteChildren(), called in C:\xampp\htdocs\aacet\app\Controllers\User.php on line 55 and defined in C:\xampp\htdocs\aacet\app\Models\UserModel.php on line 39</p><p>Error on Apr 09, 2018 17:27PM - ksort() expects parameter 1 to be array, null given in C:\xampp\htdocs\aacet\app\Helpers\Database.php on line 195</p><p>Error on Apr 09, 2018 17:28PM - Missing argument 2 for Models\UserModel::deleteChildren(), called in C:\xampp\htdocs\aacet\app\Controllers\User.php on line 55 and defined in C:\xampp\htdocs\aacet\app\Models\UserModel.php on line 39</p><p>Error on Apr 09, 2018 18:03PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_view.php on line 40</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:11PM</p>

           <p><strong>Message:</strong> syntax error, unexpected end of file</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\views\n_view.php</p>

           <p><strong>Line:</strong> 53</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Controllers\User.php(72): Core\View::render('n_view', Array)
#1 [internal function]: Controllers\User->showAllDetails()
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#4 C:\xampp\htdocs\aacet\app\Core\routes.php(33): Core\Router::dispatch()
#5 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#6 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:11PM</p>

           <p><strong>Message:</strong> syntax error, unexpected end of file</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\views\n_view.php</p>

           <p><strong>Line:</strong> 53</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Controllers\User.php(72): Core\View::render('n_view', Array)
#1 [internal function]: Controllers\User->showAllDetails()
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#4 C:\xampp\htdocs\aacet\app\Core\routes.php(33): Core\Router::dispatch()
#5 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#6 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:21PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadHeader()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 86</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:21PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:22PM</p>

           <p><strong>Message:</strong> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aacet_db.adminlogin' doesn't exist</p>

           <p><strong>Code:</strong> 42S02</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Helpers\Database.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Helpers\Database.php(109): PDOStatement->execute()
#1 C:\xampp\htdocs\aacet\app\Models\UserModel.php(48): Helpers\Database->select('SELECT * FROM a...', Array)
#2 C:\xampp\htdocs\aacet\app\Controllers\User.php(89): Models\UserModel->getPassword1('qwerty')
#3 [internal function]: Controllers\User->changePassword()
#4 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#6 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#7 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:22PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:22PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:23PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:23PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:23PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:23PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:23PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 18:24PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(35): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<p>Error on Apr 09, 2018 18:24PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\aacet\app\views\n_preview.php on line 129</p><p>Error on Apr 09, 2018 18:27PM - require(C:\xampp\htdocs\aacet\app/views/.php): failed to open stream: No such file or directory in C:\xampp\htdocs\aacet\app\Core\View.php on line 34</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:23PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:24PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:24PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:24PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:24PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:24PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:25PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:32PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:34PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:38PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:40PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:40PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:40PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:42PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:43PM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Helpers\Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Helpers\Database.php(137): PDOStatement->execute()
#1 C:\xampp\htdocs\aacet\app\Models\AuthModel.php(15): Helpers\Database->insert('details', Array)
#2 C:\xampp\htdocs\aacet\app\Controllers\Auth.php(66): Models\AuthModel->register(Array)
#3 [internal function]: Controllers\Auth->register()
#4 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#7 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 09, 2018 19:50PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 11, 2018 8:46AM</p>

           <p><strong>Message:</strong> SQLSTATE[HY000] [1049] Base 'aacet_db' inconnue</p>

           <p><strong>Code:</strong> 1049</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Helpers\Database.php</p>

           <p><strong>Line:</strong> 62</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Helpers\Database.php(62): PDO->__construct('mysql:host=loca...', 'root', '')
#1 C:\xampp\htdocs\aacet\app\Core\Model.php(33): Helpers\Database::get()
#2 C:\xampp\htdocs\aacet\app\Controllers\Auth.php(15): Core\Model->__construct()
#3 C:\xampp\htdocs\aacet\app\Core\Router.php(122): Controllers\Auth->__construct(NULL)
#4 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#5 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#6 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#7 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 11, 2018 8:50AM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 105</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 11, 2018 23:27PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 131</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 11, 2018 23:35PM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1048 Le champ 'username' ne peut être vide (null)</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Helpers\Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Helpers\Database.php(137): PDOStatement->execute()
#1 C:\xampp\htdocs\aacet\app\Models\AuthModel.php(25): Helpers\Database->insert('login', Array)
#2 C:\xampp\htdocs\aacet\app\Controllers\Auth.php(82): Models\AuthModel->insertLogin(Array)
#3 [internal function]: Controllers\Auth->register()
#4 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#7 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 11, 2018 23:39PM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicata du champ '7458963214' pour la clef 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Helpers\Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Helpers\Database.php(137): PDOStatement->execute()
#1 C:\xampp\htdocs\aacet\app\Models\AuthModel.php(15): Helpers\Database->insert('details', Array)
#2 C:\xampp\htdocs\aacet\app\Controllers\Auth.php(66): Models\AuthModel->register(Array)
#3 [internal function]: Controllers\Auth->register()
#4 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#7 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 12, 2018 1:00AM</p>

           <p><strong>Message:</strong> Call to a member function upPic() on null</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 83</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->edit()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 12, 2018 1:02AM</p>

           <p><strong>Message:</strong> Call to a member function upPic() on null</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 83</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->edit()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 12, 2018 1:10AM</p>

           <p><strong>Message:</strong> Call to a member function upPic() on null</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 83</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->edit()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 12, 2018 1:10AM</p>

           <p><strong>Message:</strong> Call to a member function upPic() on null</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 83</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->edit()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 12, 2018 21:44PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\User::make_thumb()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\User.php</p>

           <p><strong>Line:</strong> 75</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\User->edit()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<p>Error on Apr 12, 2018 22:19PM - unlink(docs/images/1523551473.jpg): No such file or directory in C:\xampp\htdocs\aacet\app\Controllers\User.php on line 84</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 12, 2018 22:26PM</p>

           <p><strong>Message:</strong> Call to undefined method Models\AdminModel::upPic()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 81</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->update()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<p>Error on Apr 12, 2018 22:28PM - unlink(docs/images/): Permission denied in C:\xampp\htdocs\aacet\app\Controllers\Admin.php on line 83</p><p>Error on Apr 12, 2018 22:32PM - unlink(docs/images/): Permission denied in C:\xampp\htdocs\aacet\app\Controllers\Admin.php on line 83</p><p>Error on Apr 12, 2018 22:36PM - unlink(1523552799.jpg): No such file or directory in C:\xampp\htdocs\aacet\app\Controllers\User.php on line 85</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 12, 2018 22:59PM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<p>Error on Apr 12, 2018 23:25PM - move_uploaded_file(docs/images/2018-04-12 23:25:50.jpg): failed to open stream: No such file or directory in C:\xampp\htdocs\aacet\app\Controllers\Admin.php on line 73</p><p>Error on Apr 12, 2018 23:44PM - unlink(docs/images/): Permission denied in C:\xampp\htdocs\aacet\app\Controllers\Admin.php on line 116</p><h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 13, 2018 0:01AM</p>

           <p><strong>Message:</strong> Call to undefined method Controllers\Admin::loadFooter()</p>

           <p><strong>Code:</strong> 0</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Controllers\Admin.php</p>

           <p><strong>Line:</strong> 142</p>

           <h3>Stack trace:</h3>

           <pre>#0 [internal function]: Controllers\Admin->changePassword()
#1 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#3 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#4 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#5 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 13, 2018 0:26AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Champ 'username' inconnu dans where clause</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> C:\xampp\htdocs\aacet\app\Helpers\Database.php</p>

           <p><strong>Line:</strong> 109</p>

           <h3>Stack trace:</h3>

           <pre>#0 C:\xampp\htdocs\aacet\app\Helpers\Database.php(109): PDOStatement->execute()
#1 C:\xampp\htdocs\aacet\app\Models\AdminModel.php(69): Helpers\Database->select('SELECT * FROM d...', Array)
#2 C:\xampp\htdocs\aacet\app\Controllers\Admin.php(113): Models\AdminModel->getImage('21')
#3 [internal function]: Controllers\Admin->delete()
#4 C:\xampp\htdocs\aacet\app\Core\Router.php(124): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\aacet\app\Core\Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#6 C:\xampp\htdocs\aacet\app\Core\routes.php(39): Core\Router::dispatch()
#7 C:\xampp\htdocs\aacet\index.php(80): require('C:\\xampp\\htdocs...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 13, 2018 1:50AM</p>

           <p><strong>Message:</strong> SQLSTATE[HY000] [1045] Access denied for user 'webazzaar_karan'@'localhost' (using password: YES)</p>

           <p><strong>Code:</strong> 1045</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 62</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(62): PDO->__construct('mysql:host=loca...', 'webazzaar_karan', '********')
#1 /home/webazzaar/public_html/aacet/app/Core/Model.php(33): Helpers\Database::get()
#2 /home/webazzaar/public_html/aacet/app/Controllers/Auth.php(15): Core\Model->__construct()
#3 /home/webazzaar/public_html/aacet/app/Core/Router.php(122): Controllers\Auth->__construct(NULL)
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#5 /home/webazzaar/public_html/aacet/app/Core/routes.php(39): Core\Router::dispatch()
#6 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#7 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 13, 2018 9:44AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'image' in 'field list'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 181</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(181): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/UserModel.php(58): Helpers\Database->update('details', Array, Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/User.php(83): Models\UserModel->upPic(Array, '1')
#3 [internal function]: Controllers\User->edit()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(39): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 13, 2018 9:45AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'image' in 'field list'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 181</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(181): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/UserModel.php(58): Helpers\Database->update('details', Array, Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/User.php(83): Models\UserModel->upPic(Array, '1')
#3 [internal function]: Controllers\User->edit()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Use...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(39): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 13, 2018 11:13AM</p>

           <p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'image' in 'field list'</p>

           <p><strong>Code:</strong> 42S22</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 181</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(181): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AdminModel.php(60): Helpers\Database->update('details', Array, Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Admin.php(81): Models\AdminModel->upPic(Array, '1')
#3 [internal function]: Controllers\Admin->update()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(39): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 22, 2018 1:46AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9447035620' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AdminModel.php(76): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Admin.php(154): Models\AdminModel->register(Array)
#3 [internal function]: Controllers\Admin->addMember()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(40): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 22, 2018 1:47AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9447035620' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AdminModel.php(76): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Admin.php(154): Models\AdminModel->register(Array)
#3 [internal function]: Controllers\Admin->addMember()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(40): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 22, 2018 1:47AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9447035620' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AdminModel.php(76): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Admin.php(154): Models\AdminModel->register(Array)
#3 [internal function]: Controllers\Admin->addMember()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(40): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 22, 2018 2:01AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9446845708' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AdminModel.php(76): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Admin.php(154): Models\AdminModel->register(Array)
#3 [internal function]: Controllers\Admin->addMember()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(40): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 22, 2018 17:13PM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9447035620' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AdminModel.php(76): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Admin.php(154): Models\AdminModel->register(Array)
#3 [internal function]: Controllers\Admin->addMember()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(40): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 23, 2018 16:02PM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9995400046' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AuthModel.php(15): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Auth.php(66): Models\AuthModel->register(Array)
#3 [internal function]: Controllers\Auth->register()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(40): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 23, 2018 16:03PM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9995400046' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AuthModel.php(15): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Auth.php(66): Models\AuthModel->register(Array)
#3 [internal function]: Controllers\Auth->register()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(40): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 23, 2018 17:20PM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '+919892575036' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AuthModel.php(15): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Auth.php(66): Models\AuthModel->register(Array)
#3 [internal function]: Controllers\Auth->register()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(40): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 24, 2018 1:12AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9892575036' for key 'username'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 181</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(181): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/TasksModel.php(12): Helpers\Database->update('login', Array, Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Tasks.php(28): Models\TasksModel->updateUsername(Object(stdClass))
#3 [internal function]: Controllers\Tasks->removeSpace()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Tas...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(41): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 24, 2018 7:15AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8301037318' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AuthModel.php(15): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Auth.php(66): Models\AuthModel->register(Array)
#3 [internal function]: Controllers\Auth->register()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(41): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 24, 2018 7:16AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8301037318' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AuthModel.php(15): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Auth.php(66): Models\AuthModel->register(Array)
#3 [internal function]: Controllers\Auth->register()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(41): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> Apr 24, 2018 10:15AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8301037318' for key 'phone1'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AuthModel.php(15): Helpers\Database->insert('details', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Auth.php(66): Models\AuthModel->register(Array)
#3 [internal function]: Controllers\Auth->register()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Aut...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(41): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<h3>Exception information:</h3>

           <p><strong>Date:</strong> May 02, 2018 11:54AM</p>

           <p><strong>Message:</strong> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '+919446919807' for key 'username'</p>

           <p><strong>Code:</strong> 23000</p>

           <p><strong>File:</strong> /home/webazzaar/public_html/aacet/app/Helpers/Database.php</p>

           <p><strong>Line:</strong> 137</p>

           <h3>Stack trace:</h3>

           <pre>#0 /home/webazzaar/public_html/aacet/app/Helpers/Database.php(137): PDOStatement->execute()
#1 /home/webazzaar/public_html/aacet/app/Models/AdminModel.php(86): Helpers\Database->insert('login', Array)
#2 /home/webazzaar/public_html/aacet/app/Controllers/Admin.php(385): Models\AdminModel->insertLogin(Array)
#3 [internal function]: Controllers\Admin->addAdmin()
#4 /home/webazzaar/public_html/aacet/app/Core/Router.php(124): call_user_func_array(Array, Array)
#5 /home/webazzaar/public_html/aacet/app/Core/Router.php(214): Core\Router::invokeObject('Controllers\\Adm...')
#6 /home/webazzaar/public_html/aacet/app/Core/routes.php(49): Core\Router::dispatch()
#7 /home/webazzaar/public_html/aacet/index.php(80): require('/home/webazzaar...')
#8 {main}</pre>

           <hr />
<p>Error on Jul 06, 2018 0:09AM - require(C:\xampp\htdocs\viswapranavam2\app/views/give page path here.php): failed to open stream: No such file or directory in C:\xampp\htdocs\viswapranavam2\app\Core\View.php on line 34</p><p>Error on Jul 06, 2018 0:45AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 0:47AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 0:47AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 0:47AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 0:47AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 0:47AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 0:47AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 0:49AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 0:49AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 21:21PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 21:22PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 21:25PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 21:26PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 21:26PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 21:26PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 21:26PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 17</p><p>Error on Jul 06, 2018 21:27PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 18</p><p>Error on Jul 06, 2018 21:28PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 21</p><p>Error on Jul 06, 2018 21:28PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 21</p><p>Error on Jul 06, 2018 21:28PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 21</p><p>Error on Jul 06, 2018 21:30PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 21</p><p>Error on Jul 06, 2018 21:47PM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 21</p><p>Error on Jul 07, 2018 9:45AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 30</p><p>Error on Jul 07, 2018 9:45AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 32</p><p>Error on Jul 07, 2018 9:46AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 29</p><p>Error on Jul 07, 2018 9:46AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 33</p><p>Error on Jul 07, 2018 10:55AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 33</p><p>Error on Jul 07, 2018 10:55AM - Invalid argument supplied for foreach() in C:\xampp\htdocs\viswapranavam2\app\views\admin\userView.php on line 33</p>